[package]
name = "ricochet-robots"
version = "0.1.0"
authors = ["satos"]
edition = "2018"

[dependencies]
rand = "0.7.0"
atoi = "0.3.1"
itertools = "0.8.0"
xorshift = "0.1.3"
time = "0.1.42"

[[bin]]
name = "ricochet_robot_problem_generator"
path = "src/main.rs"

[[bin]]
name = "ricochet_robot_benchmarker"
path = "src/benchmarker.rs"
